### PR TITLE
Add artogahr

### PR DESCRIPTION
**Pull request by artogahr**
The markdown file must fulfill these conditions:

- [X] The name of the readme file is your **username.md** if you are making a new creative readme.
- [ ] The name of the readme file is the person's username from where it is inspired from.
- [X] The bottom of the readme file contains: `⭐️ From [username](https://github.com/[username])`

### CODE REVIEW

**Comment by DeltaCoderr** [comment]
Looking Good

**Comment by artogahr** [comment]
Thanks man, but even though my changes were merged I still can't find my readme (artogahr.md) in the original repository in short-and-sweet folder, why do you think that is?

**Comment by DeltaCoderr** [comment]
This isn't merged yet, I just approved this. The Owner of this repo has to see it and merge it 
P.S - They were busy for few days so they said they will merge the PR asap they get free time

**Comment by artogahr** [comment]
> This isn't merged yet, I just approved this. The Owner of this repo has to see it and merge it
> P.S - They were busy for few days so they said they will merge the PR asap they get free time

Oh ok lol I should've noticed that.
Take your time @kautukkundan no rush bro

**Pull request closed without merging**
