### PR TITLE
added OSouravdey777.md file

### PR DESCRIPTION
**Pull request by Souravdey777**
The markdown file must fulfill these conditions:

- [x] The name of the readme file is your **username.md** if you are making a new creative readme.
- [x] The name of the readme file is the person's username from where it is inspired from.
- [x] The bottom of the readme file contains: `⭐️ From [username](https://github.com/[username])`

### CODE REVIEW

**Comment by DeltaCoderr** [comment]
Change the title of this Pull Request Btw.

**Comment by Souravdey777** [comment]
Is it fine??

**Comment by DeltaCoderr** [comment]
Yep 👍

**Comment by DeltaCoderr** [comment]
You forgot to add ``⭐️ From [username](https://github.com/[username])``

**Pull request merged**
