### PR TITLE
Abstract Added- VedantKhairnar added

### PR DESCRIPTION
**Pull request by VedantKhairnar**
The markdown file must fulfill these conditions:

- [x] The name of the readme file is your **username.md** if you are making a new creative readme.
- [x] The name of the readme file is the person's username from where it is inspired from.
- [x] The bottom of the readme file contains: `⭐️ From [username](https://github.com/[username])`

### CODE REVIEW

**Comment by kautukkundan** [comment]
Hey @VedantKhairnar Thank you for the contribution
I am curious to know why did you create a new topic?

**Comment by VedantKhairnar** [comment]
You mean the new folder - Abstract
Just had to add the folder(with file) instead of just adding the file.

**Comment by kautukkundan** [comment]
Thank you Vedant, it has been possible only because of the awesome dev community and contributors like you 😄
For the topic, it's really nice to see such a vivid readme, pick whichever you feel is most relevant to your readme.

**Comment by VedantKhairnar** [comment]
Done.
Thanks!!
: )

**Pull request merged**
