### PR TITLE
Add SatYu26.md

### PR DESCRIPTION
**Pull request by SatYu26**
The markdown file must fulfill these conditions:

- [x] The name of the readme file is your **username.md** if you are making a new creative readme.
- [x] The name of the readme file is the person's username from where it is inspired from.
- [x] The bottom of the readme file contains: `⭐️ From [username](https://github.com/[username])`

### CODE REVIEW

**Comment by DeltaCoderr** [comment]
You forgot Two things :
* You forgot to add ``⭐️ From [username](https://github.com/[username])``
* Change the title of the PR

**Comment by SatYu26** [comment]
> You forgot Two things :
> 
> * You forgot to add `⭐️ From [username](https://github.com/[username])`
> * Change the title of the PR

I have added the 1st one i guess please have a look.
and i will change PR name right now.

**Comment by SatYu26** [comment]
> You forgot Two things :
> 
> * You forgot to add `⭐️ From [username](https://github.com/[username])`
> * Change the title of the PR

what should be the name of PR??

**Comment by DeltaCoderr** [comment]
``Add SatYu26.md ``?

**Pull request closed without merging**
