### PR TITLE
create Itsbeenalongday readme

### PR DESCRIPTION
**Pull request by Itsbeenalongday**
The markdown file must fulfill these conditions:

- [x] The name of the readme file is your **username.md** if you are making a new creative readme.
- [x] The name of the readme file is the person's username from where it is inspired from.
- [x] The bottom of the readme file contains: `⭐️ From [username](https://github.com/[username])`

### CODE REVIEW

**Comment by DeltaCoderr** [comment]
You forgot ``⭐️ From [username](https://github.com/[username])`` this

**Comment by Itsbeenalongday** [comment]
oh i forgot it thanks!

**Review by DeltaCoderr — APPROVED** [review]
👍

**Comment by Itsbeenalongday** [comment]
thanks!

**Pull request merged**
