### PR TITLE
Add SatYu26.md

### PR DESCRIPTION
**Pull request by SatYu26**
The markdown file must fulfill these conditions:

- [x] The name of the readme file is your **username.md** if you are making a new creative readme.
- [x] The name of the readme file is the person's username from where it is inspired from.
- [x] The bottom of the readme file contains: `⭐️ From [username](https://github.com/[username])`

I have added few new changes again.

### CODE REVIEW

**Comment by DeltaCoderr** [comment]
Is this Final then?

**Comment by SatYu26** [comment]
> Is this Final then?

Yeah its final. actually one workflow was conflicting with my original repo so had to change it. Thanks

**Comment by DeltaCoderr** [comment]
Aight then 👍

**Review by DeltaCoderr — APPROVED** [review]

**Comment by SatYu26** [comment]
> Aight then 👍

when will it be merged?

**Comment by DeltaCoderr** [comment]
Once the github repo owner enters and checks it. They were busy for some days so they will merge it asap once they come in

**Comment by SatYu26** [comment]
> Once the github repo owner enters and checks it. They were busy for some days so they will merge it asap once they come in

ok thanks

**Pull request merged**
