### PR TITLE
feat: ✨ rodrigograca31 (animated Matrix SVG)

### PR DESCRIPTION
**Pull request by rodrigograca31**
The markdown file must fulfill these conditions:

- [x] The name of the readme file is your **username.md** if you are making a new creative readme.
- [x] The name of the readme file is the person's username from where it is inspired from.
- [x] The bottom of the readme file contains: `⭐️ From [username](https://github.com/[username])`

### CODE REVIEW

**Comment by kautukkundan** [comment]
Hey @rodrigograca31 
Thanks for your contribution
Could you please move this to multimedia

**Comment by rodrigograca31** [comment]
Sure! 
I didn't notice that category and thought this one was the best but it isn't! :)

**Comment by rodrigograca31** [comment]
Done. :raised_hands:

**Comment by rodrigograca31** [comment]
Thanks ❤️

**Pull request merged**
